### ISSUE TITLE
Python 3.6 fails on dumping the json when sort_keys=True

### ISSUE THREAD

**Issue by rbval** [hCaptcha/hmt-escrow#32]
A call to our storage upload function where we do the json dump with sorting the keys on None values fails: https://github.com/hCaptcha/hmt-escrow/blob/master/api/storage.py#L46

The traceback:
```
(hash_, url) = upload(results, public_key)
File "/usr/local/lib/python3.6/dist-packages/api/storage.py", line 46, in upload
manifest_ = json.dumps(msg, sort_keys=True, ensure_ascii=True)
File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
  **kw).encode(obj)
File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
  chunks = self.iterencode(o, _one_shot=True)
File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
  return _iterencode(o, 0)
TypeError: '<' not supported between instances of 'NoneType' and 'str'
[2018-11-26 21:56:42,018] [] [ERROR] [172.22.0.13] Unable to do database operation because:'<' not supported between instances of 'NoneType' and 'str'
```

We did some debugging with @todicus and noticed that that Python 3.6 doesn't know how to sort keys that have `None` values. However, this has been fixed in Python 3.7.

If we delete the `sort_keys=True` we actually dodge the issue. Any thoughts @todicus @posix4e ?

Transferring the discussion here

**Comment by todicus** [comment]
Should be fine. We will need to remember to sort after loading stored results before comparing to fixtures in any tests down the line.

**Comment by gaieges** [comment]
Are you sure it's a 3.6 issue?  Seems to work for me in the narrow case:

```
$ docker run -it --rm python:3.6-alpine
Python 3.6.7 (default, Nov 16 2018, 06:52:39)
[GCC 6.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> d = {'blah': None, 'goat': 'true'}
>>> import json
>>> json.dumps(d, sort_keys=True)
'{"blah": null, "goat": "true"}'
```

**Comment by gaieges** [comment]
Ahh, it is a `None` Key that's causing the problem:

```
>>> d = {
...   'ethereum_addresses': {
...     '0xA62a1c18571B869e43EEAbD217e233E7F0275AF3': {
...       'count': 63, 'correct': 63
...     },
...     None: {
...       'count': 12, 'correct': 9
...     }
...   }
... }
>>>
>>> d
{'ethereum_addresses': {'0xA62a1c18571B869e43EEAbD217e233E7F0275AF3': {'count': 63, 'correct': 63}, None: {'count': 12, 'correct': 9}}}
>>> json.dumps(d, sort_keys=True, ensure_ascii=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
TypeError: '<' not supported between instances of 'NoneType' and 'str'
```

I think the better question is - should it be getting that None as a key?

**Comment by rbval** [comment]
Good point @gaieges , will take a look at the logic doing that, maybe the fix is there.
